version: "3.5"
services:
  autfinal:
    container_name: autfinal
    build: 
      context: .
    restart: unless-stopped
    command: "./autfinal"
    ports:
      - "8080:8080"
    volumes:
      - ./images:/autfinal/static/images
    depends_on:
      - postgres

  postgres:
    image: postgres:10.5
    restart: unless-stopped
    ports:
      - "5433:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./images:/home/ubuntu/static/images
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - "autfinal"
