version: "3.5"
services:
  autfinal:
    container_name: autfinal
    build: 
      context: .
    restart: unless-stopped
    command: "./autfinal"
    ports:
      - "8080:8080"
    volumes:
      - /home/artyom/autfinal/static/images:/autfinal/static/images
    depends_on:
      - postgres
  
  postgres:
    image: postgres:10.5
    restart: always
    #env_file:
    #  - /home/artyom/DiplomaBackend/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-data: