version: "3.5"
services:
  autfinal:
    container_name: autfinal
    build: 
      context: .
    restart: unless-stopped
    command: "./autfinal"
    ports:
      - "8080:8080"
    volumes:
      - /home/artyom/autfinal/static/images:/autfinal/static/images
    depends_on:
      - postgres
  
  postgres:
    image: postgres:10.5
    restart: always
    #env_file:
    #  - /home/artyom/DiplomaBackend/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - /autfinalVolumes/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
  nginx:
     image: nginx:mainline-alpine
     ports:
       - "80:80"
     restart: unless-stopped
     volumes:
       - /home/artyom/autfinal/static/images:/home/ubuntu/static/images
       - web-root:/var/www/html
       - ./config/nginx:/etc/nginx/conf.d
       - certbot-etc:/etc/letsencrypt
       - certbot-var:/var/lib/letsencrypt
     depends_on:
       - "autfinal"

volumes:
  web-root:
  certbot-etc:
  certbot-var: