server:
  port: "8080"
  name: "https://lostpointer.tech"

postgres:
  port: 5433
  host: "localhost"
  user: "a_shirshov"
  database: "autfinal"

#img_path:
#  "/autfinal/static/images"

img_path:
  "/home/artyom/static/images"