server:
  port: "8080"
  name: "https://lostpointer.tech"

postgres:
  port: 5432
  host: "postgres"
  user: "a_shirshov"
  database: "autfinal"

img_path:
  "/autfinal/static/images"

#img_path:
# "/home/artyom/static/images"